Fp-13 Sidebar Component
caarlosdamian/covid-cases pull request #29
Opened 2022-08-19 14:15 UTC by DiegoVillasenorVilla

PR checklist

### Description

- I created an isolated Sidebar component this will be used later on in the application.

- The component had be test by react testing library

- The sidebar component has two props: ISidebarMenuItem and ISidebarMenuCard.

     - The first one is compose with the next properties: id, label, icon and url.
     - ISidebarMenuCard is compose with the next propesties: id, displayName, photoUrl

But this two props will could be adapted to the needs of the project

- The sidebar have two states, that are controled with a class with a boolean: collapsed an expanded

![image](https://user-images.githubusercontent.com/50335824/185638095-98f3dc37-0137-491d-9c08-d51ba8791a50.png)

![image](https://user-images.githubusercontent.com/50335824/185638168-a4368c2b-aeba-4a11-86d0-c6a00245c99e.png)

### Testing Checklist

- [] Test cases have been added/updated
- [] Tested locally in browser (at least one other than Chrome)
- [] All tests pass

### What JIRA Ticket(s) does this PR address?

- [FP-13](https://cd95.atlassian.net/browse/FP-13)

2022-08-19 14:55 UTC, caarlosdamian requested changes
algunos comentarios

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/ISiderbarMenuItem.ts
> +import {
Este archivo va en utils.

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenuCardView.tsx
> +          {' '}
Eliminar esto

2022-08-19 14:55 UTC, caarlosdamian commented on src/utils/classes.ts
> +export function classNames(...args: string[]): string {
Para que usas esto ??? no es necesario

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/ISidebarMenuCard.ts
> +export const card: ISidebarMenuCard = {
Esto va en Utils

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.Search-content-collapsed{
no usar mayuzculas en clases

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.tsx
> +      className={classNames('SidebarMenu', isOpen ? 'expanded' : 'collapsed')}
className ={isOpen ? 'expanded' : 'collapsed'}

eliminar la funcion className no es necesaria

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenuCardView.tsx
> +      <div className={classNames('profileInfo', isOpen ? '' : 'collapsed')}>
Eliminar la fucion classNames 

className={`profileInfo ${isOpen && ' '  || 'collapsed'}

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenuItemView.tsx
> +        <div className={classNames('ItemContent', isOpen ? '' : 'collapsed')}>
Eliminar la funcion classNames 
className={`ItemContent ${isOpen ? '':'collapsed'}

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarPage.tsx
> +  const items: ISidebarMenuItem[] = [
esta parte va en Utils

2022-08-19 14:55 UTC, caarlosdamian commented on src/utils/classes.ts
> +export function classNames(...args: string[]): string {
Eliminar no es necesaria.

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.tsx
> +  function handleClick() {
user nomenclature 
const handleToggle = () =>{
setIsOpen(!isOpen)
}

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.tsx
> +export function SidebarMenu({ items, card }: SidebarMenuProps) {
export const SidebarMenu = () =>{

}

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/DataGrid.tsx
>  export function DataGrid() {
export const DataGrid =()=>{}

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenuCardView.tsx
> +export function SidebarMenuCardView({
export const SidebarMenuCardview = () => {}

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenuItemView.tsx
> +export function SidebarMenuItemView({
export const SidebarMenuItemView = () => {}

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarPage.tsx
> +export function SidebarPage() {
export const SidebarPage = () =>{}

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarPage.tsx
> +  const card: ISidebarMenuCard = {
Esto va en utils

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +    flex: 2;
Elimina el flex:2 maybe elimine el espacio que queda al momento de ser colapse

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.SidebarMenu{
no usar mayuzculas ni camelCase sidebar-menu

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.menu-button{
sidebar__menu-button

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.hamburgerbutton{
sidebar__hambuerger-button

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.Search-content-collapsed{
sidebar__search-content--collapsed

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.Search-content-expanded{
sidebar__content--expanded

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.search-input{
sidebar__search-input

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.search-icon{
sidebar__search-icon

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.input-search{
sidebar__input-search

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.SidebarMenuItemView{
sidebar__menu-item-view

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.ItemContent{
sidebar__item-content

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.label{
sidebar__label

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.SidebarMenuCardView{
sidebar__menu-card-view

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.profile{
sidebar__profile--img

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.profileInfo{
sidebar__profile-info

2022-08-19 14:55 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu.scss
> +.name{
sidebar__name

2022-08-22 20:46 UTC, DiegoVillasenorVilla commented on src/utils/classes.ts
> +export function classNames(...args: string[]): string {
Lo usaba para la classname, para cuando era collapsed o se expandia

2022-08-25 02:34 UTC, closed without merging