[FP-18] Login Functionality with Redux
caarlosdamian/covid-cases pull request #32
Opened 2022-09-04 07:54 UTC by thisisofficial

### Description

This feature was a long time comming, and it's finally done.
With this, the backend for our auth system gets a request from our ap to return
encrypted credentials for us to use.

- Added a mutation query to the backend API
- Configured our app-wide store to use new fetch request

### Testing Checklist

- [] Test cases have been added/updated
- [x] Tested locally in browser (at least one other than Chrome)
- [x] All tests pass

### What JIRA Ticket(s) does this PR address?

- [FP-18](https://cd95.atlassian.net/browse/FP-18)

2022-09-04 19:10 UTC, caarlosdamian requested changes
Check test are failing

2022-09-09 14:09 UTC, caarlosdamian requested changes

2022-09-09 14:09 UTC, caarlosdamian commented on src/pages/Login/Login.tsx
>  import './Login.scss';
move this to line 11

2022-09-09 14:09 UTC, caarlosdamian commented on src/routes/routes.tsx
> +                user={loginState.user.isLogged}
use just isLogged

2022-09-09 14:09 UTC, caarlosdamian commented on src/routes/routes.tsx
>    const loginState = useSelector((state: IState) => state.loginSlice);
use destructuring const {isLogged} = useSelector((state: IState) => state.loginSlice.user);

2022-09-09 14:09 UTC, caarlosdamian commented on src/pages/Login/Login.test.tsx
> +    render(
this is already in test-utils.tsx please remove it

2022-09-09 14:09 UTC, caarlosdamian commented on src/pages/Login/Login.tsx
>  import './Login.scss';
this already isnt good move it to line styling imports should be last

2022-09-09 14:09 UTC, caarlosdamian commented on src/routes/routes.tsx
>    const loginState = useSelector((state: IState) => state.loginSlice);
this still the same use destructuring

2022-09-09 14:09 UTC, caarlosdamian commented on src/routes/routes.tsx
> +                user={loginState.user.isLogged}
please check comments

2022-09-09 15:12 UTC, thisisofficial commented on src/pages/Login/Login.test.tsx
> +    render(
> this is already in test-utils.tsx please remove it

I cant find said file. Care to direct me to it?.
It was also changed to pass tests, so now its a bit different.

2022-09-11 22:55 UTC, caarlosdamian approved these changes

2022-09-11 22:55 UTC, merged