Fp-21 Card component
caarlosdamian/covid-cases pull request #33
Opened 2022-09-09 19:00 UTC by DiegoVillasenorVilla

PR checklist

### Description

- Card isolated component added to the app
-  card component have two props: label: string and value:number
- the desing is similar to the figma desing
- test added
- responsive desing of the card component (min-width: 414px and max-width: 820px) and content component added (min-width: 414px and max-width: 820px)

![image](https://user-images.githubusercontent.com/50335824/189424371-8f91eb1c-5f29-42f0-9972-97de95446d0c.png)
![image](https://user-images.githubusercontent.com/50335824/189424415-336735fd-e5bf-4865-a929-5670cade4275.png)
![image](https://user-images.githubusercontent.com/50335824/189424453-fa61e01e-8497-4cd8-9d5c-88b3cb315a63.png)
![image](https://user-images.githubusercontent.com/50335824/189424498-bb881f30-62bc-48fa-85b4-f3f76fe4bc6f.png)

### Testing Checklist

- [x] Test cases have been added/updated
- [x] Tested locally in browser (at least one other than Chrome)
- [x] All tests pass

### What JIRA Ticket(s) does this PR address?

- [FP-21](https://cd95.atlassian.net/browse/FP-21)

2022-09-11 23:22 UTC, caarlosdamian requested changes
Algunos comentarios , cualqueir duda podemos checarlo en slack

2022-09-11 23:22 UTC, caarlosdamian commented on index.html
> +      @import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
Este archivo dejarlo como estaba porque el link ya tenia todas las fuentes necesarias 

`      @import url('https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap');
`

2022-09-11 23:22 UTC, caarlosdamian commented on src/components/card/card.scss
> +  width: 15vw;
Utilizar pixeles o rems

2022-09-11 23:22 UTC, caarlosdamian commented on src/components/card/card.scss
> +    display: flex;
Agregar propiedades para centrar los items 

justify-content 
aling-items

2022-09-11 23:22 UTC, caarlosdamian commented on src/components/card/card.scss
> +      font-family: Mulish;
Esta fuente no esta importada por lo tanto la app no la esta tomando , importarla de igual manera en index.html bsucar la fuente en Google fonts

2022-09-11 23:22 UTC, caarlosdamian commented on src/components/card/card.scss
> +    width: 25vw;
Utilizar rems o pixeles

2022-09-11 23:22 UTC, caarlosdamian commented on src/components/card/card.test.tsx
> +    expect(screen.getByTestId('card-testing')).toBeDefined();
Agregar test que se renderiza el label 'To do'

2022-09-11 23:22 UTC, caarlosdamian commented on src/components/card/card.tsx
> +    <div className="card-item" data-testid="card-testing">
Este contenedor es innecesario

2022-09-11 23:22 UTC, caarlosdamian commented on src/components/card/card.tsx
> +      <div className="card-content-info">
Este contenedor es innecesario

2022-09-11 23:22 UTC, caarlosdamian commented on src/components/card/card.tsx
> +  <div className="card-container">
Solo es necesario un contenedor 

`<div className="card-container">
        <span className="card-label">{label}</span>
        <p className="card-value">{value}</p>
      </div>`

2022-09-11 23:22 UTC, caarlosdamian commented on src/components/content/Content.scss
> +        width: 50vw;
Utilizar rems o pixeles

2022-09-11 23:22 UTC, caarlosdamian commented on src/components/sidebar/SidebarMenu/SidebarMenu.scss
> -  .search-content-collapsed {
Esto ya no se utiliza??

2022-09-11 23:22 UTC, caarlosdamian commented on src/components/card/card.tsx
> +  <div className="card-container">
Realizar el diseno de figma 
mismo alto y ancho 
258px por 134px

2022-09-11 23:22 UTC, caarlosdamian commented on src/components/card/card.tsx
> +  <div className="card-container">
Checar a detalle el diseno y verificar que hagan match
<img width="238" alt="Screen Shot 2022-09-11 at 18 09 23" src="https://user-images.githubusercontent.com/6474358/189552856-5a80f5fe-172e-4ea8-8fe5-4f1d2a3e178f.png">
Figma 
<img width="371" alt="Screen Shot 2022-09-11 at 18 09 39" src="https://user-images.githubusercontent.com/6474358/189552865-658d47da-9bda-464c-a0be-20d0adf3f67c.png">

2022-09-11 23:22 UTC, caarlosdamian commented on src/components/card/card.scss
> +@media (min-width: 414px) and (max-width: 820px) {
esto hace que menos de 414px no tenga mas diseno y no es responsive hacer dos media queries para que no se combinen disenos y abarcar todo 
![Screen Shot 2022-09-11 at 18 16 30](https://user-images.githubusercontent.com/6474358/189553098-3f01941f-3fef-4d93-a242-d36bbe68affa.png)

(max-width: 820px)
(max-width: 430px) -> iphone 12 Pro max  es de esta dimenciones queremos abarcar todos los dispositivos por lo menos apple

2022-09-11 23:22 UTC, caarlosdamian commented on src/components/table/Table.scss
> +  width: 100%;
No hacer cambios a Table.scss si el ticket no trata de este component. 

asi no alargamos el scope

2022-09-11 23:22 UTC, caarlosdamian commented on src/main.tsx
> +      <PersistGate loading={null} persistor={persistor}>
Esto es de otro ticket que no?? hay que bajar master

2022-09-11 23:22 UTC, caarlosdamian commented on src/main.tsx
> +      <PersistGate loading={null} persistor={persistor}>
Eliminar estos cambios

2022-09-11 23:22 UTC, caarlosdamian commented on package.json
> +    "redux": "^4.2.0",
Eliminar estos cambios  Son de otro ticket , bajar master

2022-09-11 23:22 UTC, caarlosdamian commented on src/pages/Login/Login.tsx
> +import './Login.scss';
Este component no lo cambiemos si no trata del ticket

2022-09-11 23:22 UTC, caarlosdamian commented on src/pages/calendar/Calendar.tsx
> +export const Calendar = () => <div> Calendar</div>;
no hacer cambios en este componente

2022-09-11 23:22 UTC, caarlosdamian commented on src/pages/overview/overview.scss
> +@media (min-width:414px) and (max-width:820px) {
Separar los media queries

2022-09-11 23:22 UTC, caarlosdamian commented on src/pages/overview/Overview.tsx
> +import './overview.scss';
Cambiar nombre Overview.scss 

componentes y scss van en mayuzcula 

folders en minusculas

2022-09-11 23:22 UTC, caarlosdamian commented on src/redux/Store.ts
> +  loginSlice: loginSliceReducer,
Estos cambios no son relacionados a Card component

2022-09-11 23:22 UTC, caarlosdamian commented on src/routes/index.tsx
> +    id: '3',
Identar linea como las que estan por debajo

2022-09-11 23:22 UTC, caarlosdamian commented on src/pages/Login/Login.scss
> +    padding-bottom: 20px;
Eliminar estos cambios

2022-09-11 23:28 UTC, caarlosdamian commented
Resolver conflictos, revizar Grid puede facilitar el desarollo al momento que integremos las Card , pero por el momento centrar el desarollo en el componente

2022-09-13 02:20 UTC, DiegoVillasenorVilla commented on src/components/sidebar/SidebarMenu/SidebarMenu.scss
> -  .search-content-collapsed {
no esto ya no, quitamos la barra de busquedas del sidebar

2022-09-15 02:27 UTC, DiegoVillasenorVilla commented on src/main.tsx
> +      <PersistGate loading={null} persistor={persistor}>
si eso no se porque se subio si ya lo habia subido en el otro ticket

2022-09-19 14:04 UTC, caarlosdamian requested changes
some commenrs

2022-09-19 14:04 UTC, caarlosdamian commented on index.html
> +      @import url('https://fonts.googleapis.com/css2?family=Mulish&display=swap');
Este es el correcto 

`      @import url('https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap');
`

2022-09-19 14:04 UTC, caarlosdamian commented on src/components/card/card.scss
> +    font-weight: 700;
No la tienes importada checar comentario en index.html 

      @import url('https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap');

2022-09-19 14:04 UTC, caarlosdamian commented on src/components/card/card.tsx
> +import './card.scss';
Card.scss Mayuzculas

2022-09-19 14:04 UTC, caarlosdamian commented on src/pages/Login/Login.tsx
> +import './Login.css';
Debe ser scss

2022-09-19 14:04 UTC, caarlosdamian commented on src/pages/overview/Overview.tsx
> +    <CardComponent label="Unresolved" value={60} />
No son necesarias aqui aun

2022-09-19 14:04 UTC, caarlosdamian commented on src/pages/overview/overview.scss
> +    display: flex;
Overview.scss Mayuzculas al archivo

2022-09-19 14:04 UTC, caarlosdamian commented on src/routes/index.tsx
> +    id: '3',
Este comentario sigue sin ser resuelto identar lineas

2022-09-22 03:11 UTC, caarlosdamian approved these changes
lgtm

2022-09-22 03:11 UTC, merged