[FP-22] Tooltip Component
caarlosdamian/covid-cases pull request #34
Opened 2022-09-16 23:25 UTC by thisisofficial

### Description

Added a tooltip component. Can be used with two props:
 - Type: ("success":default , "warn", "error") Changes the type of tooltip,
 - Label: (string) Changes the content of the tooltip label.
 
![image](https://user-images.githubusercontent.com/93210838/190830059-df71ce32-9210-40ad-b4e7-58e7391ffdbf.png)

### Testing Checklist

- [ ] Test cases have been added/updated
- [x] Tested locally in browser (at least one other than Chrome)
- [x] All tests pass

### What JIRA Ticket(s) does this PR address?

- [FP-22](https://cd95.atlassian.net/browse/FP-22)

2022-09-19 01:19 UTC, caarlosdamian requested changes
Estos ultimos comentarios y quedaria listo

2022-09-19 01:19 UTC, caarlosdamian commented on src/components/tooltip/Tootltip.tsx
> +};
Solo falta el test del componente

2022-09-19 01:19 UTC, caarlosdamian commented on src/components/tooltip/Tootltip.tsx
> +    {' '}
Eliminar esto no es necesario

2022-09-19 01:19 UTC, caarlosdamian commented on src/components/tooltip/Tootltip.tsx
> +    {label || type}{' '}
label || type}. eliminar las llaves extras

2022-09-19 01:19 UTC, caarlosdamian commented on src/components/tooltip/Tootltip.scss
> +.tip{
Identar este documento

2022-09-19 02:03 UTC, thisisofficial commented on src/components/tooltip/Tootltip.tsx
> +};
Test ya fueron agregados en un commit mas adelante al que comentas...

2022-09-19 02:04 UTC, thisisofficial commented on src/components/tooltip/Tootltip.tsx
> +    {' '}
Done.

2022-09-19 02:04 UTC, thisisofficial commented on src/components/tooltip/Tootltip.tsx
> +    {label || type}{' '}
Done.

2022-09-20 01:39 UTC, thisisofficial commented on src/components/tooltip/Tootltip.scss
> +.tip{
Done

2022-09-20 04:06 UTC, caarlosdamian approved these changes
Lgtm

2022-09-20 04:06 UTC, merged